version: '3.7'

services:

  nginx: 
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "8080:80"
      - "443:443"
    depends_on: 
      - authapi
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

  frontend:
    image: authentication_demo/frontend:v1
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  authapi:
    image: authentication_demo/auth-api:v1
    container_name: authapi
    restart: on-failure   
    build:
      context: ../
      dockerfile: backend/AuthApi/Dockerfile
    ports:
      - "5001:5000"
    depends_on: 
      - sqlserver
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      Database__Name: "auth-db"
    env_file: 
      - ./sqlserver.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "mssQlp4ssword#"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data