apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: authentication-demo
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: authentication_demo/auth-api:v1
        env:
        - name: Database__Name
          value: "auth-db"
        - name: Database__Password
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: SA_PASSWORD     
        envFrom:
        - configMapRef:
            name: sqlserver-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: authentication-demo
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
